[package]
name = "bevy-steamworks"
version = "0.11.0"
authors = ["james7132 <contact@jamessliu.com>", "QueenOfSquiggles <thequeenofsquiggles@gmail.com>"]
edition = "2021"
description = "A Bevy plugin for integrating with the Steamworks SDK."
repository = "https://github.com/QueenOfSquiggles/bevy_steamworks"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "gamedev", "steam"]

[features]
default = []
# Enables serde from the base steamworks crate
serde = ["steamworks/serde"]
# Enables extra features that can make early development easier
dev = []

[dependencies]
bevy_log = "0.15"
bevy_app = "0.15"
bevy_ecs = "0.15"
bevy_utils = "0.15"
steamworks = { git = "https://github.com/JonnyPower/steamworks-rs.git", branch="master"}

[dev-dependencies]
bevy = "0.15"
